global:
  scrape_interval: 5s # scrape data every 5 secs

scrape_configs:
  - job_name: 'system_metrics'
    static_configs:
      - targets: ['node_exporter:9100'] # look at the "node_exporter" container
